Disable the ePUB yet again.
Due to a CI failure at
https://github.com/nnethercote/perf-book/actions/runs/6358429874/job/17270643057:
```
[2023-09-29T23:53:11Z ERROR mdbook_epub] Incompatible mdbook version got 0.4.35 expected 0.4.34
Error: -29 23:53:11 [ERROR] (mdbook::renderer): Renderer exited with non-zero return code.
Error: -29 23:53:11 [ERROR] (mdbook::utils): Error: Rendering failed
Error: -29 23:53:11 [ERROR] (mdbook::utils):    Caused By: The "epub" renderer failed
```